foa:
  num_agents: 7
  num_steps: 7
  k: 1
  backtrack: 0.5
  resampling: "linear_filtered"
  min_steps: 4
  num_evaluations: 3
  origin: 120

tot_bfs:
  num_selections: 3
  num_steps: 4
  num_evaluations: 3

tot_dfs:
  num_steps: 4
  num_selections: 3
  num_evaluations: 3
  convergence_threshold: 0.6
  pruning_threshold: 0.1
  confidence_threshold: 20
  max_iterations: 10
  convergence_count: 20

got:
  num_selections: 5
  num_steps: 4
  num_generate: 10
  num_evaluations: 3
  num_best: 2

rap:
  num_iterations: 50
  num_samples: 5
  num_evaluations: 3
  exploration_constant: 1.0

react:
  num_steps: 10