io:
  n: 1

cot:
  n: 1

cot_sc:
  n: 10
  
foa:
  num_agents: 5
  num_steps: 6
  k: 1
  backtrack: 0.5
  resampling: "linear_filtered"
  min_steps: 1
  num_evaluations: 3
  origin: 10

tot_bfs:
  num_selections: 2
  num_steps: 4
  num_evaluations: 1

tot_dfs:
  num_selections: 3
  num_steps: 5
  num_evaluations: 1
  max_iterations: 6

got:
  num_selections: 3
  num_steps: 5
  num_generate: 5
  num_evaluations: 3
  num_best: 2

react:
  num_steps: 12

rap:
  num_iterations: 10
  num_samples: 5
  num_evaluations: 3
  exploration_constant: 1.0