io:
  n: 1

cot:
  n: 1

cot_sc:
  n: 10
  
foa:
  num_agents: 3
  num_steps: 5
  k: 2
  backtrack: 0.5
  resampling: "linear_filtered"
  min_steps: 1
  num_evaluations: 3
  origin: 120

tot_dfs:
  num_selections: 3
  num_steps: 1
  num_evaluations: 3
  max_iterations: 10
  
got:
  num_selections: 3
  num_steps: 1
  num_generate: 5
  num_evaluations: 3
  num_best: 2

rap:
  num_iterations: 10
  num_samples: 5
  num_evaluations: 3
  exploration_constant: 1.0